Web translations
DemocraciaEnRed/democraciaenred-web pull request #2
Opened 2022-11-07 19:24 UTC by NicoC0

Todo el sitio traducido, incluidas las imágenes con texto en inglés que se muestran si el sitio está en inglés.

2022-11-08 15:36 UTC, guillecro commented
Buenas! Nos agregue como reviewers :)

2022-11-11 20:35 UTC, guillecro requested changes
* Fantastic work with the charts and the language reactivity. It's works so well! Congrats!
* There is an error that happens with the pictures when loading the app at first time. I'll leave details down (1)
* In one of the Hexagons, the button "Conocenos" it links to spanish, even if you're in english.
* The rest of the stuff is looking fine

(1) Do `npm run build`,  that will give you a static build of the site. Then do `npm run serve`, which will serve you the contents with a local web server. http://localhost:9000 is the url.

When you load the site, check the pictures in the homepage in the "resources" section
They... dont load... but if you switch languages, now they load! Maybe the translations are not loaded on init... we should check that out. Can you guess and fix what is happening? If you need help, let me know. Maybe there is a config that will help us.

https://user-images.githubusercontent.com/8771166/201427015-a9e93f9e-7317-4469-a527-48cb527ab523.mp4

2022-11-11 20:35 UTC, guillecro commented on src/components/ecosystem/index.js
> +                {intl.formatMessage({ id: "press.see_less" })}
No entiendo muy bien donde se ve este "boton"... en la parte de ecosistema no lo veo... me mandas una captura?

2022-11-12 00:00 UTC, NicoC0 commented on src/components/ecosystem/index.js
> +                {intl.formatMessage({ id: "press.see_less" })}
El botón no se muestra porque el componente no recibe nada de "data.link".
Esto estaba comentando desde el momento que agarramos el código, por lo que entendemos que no se usa, pero lo tradujimos por si acaso.

2022-11-16 19:29 UTC, guillecro approved these changes
Excelente PR!
Gracias por todos los cambios!

2022-11-16 19:33 UTC, guillecro commented
Veo todo listo para hacer el merge y deployear en produccion!
Gracias @NicoC0 y @GerardoDR! Trabajaron muy bien con el stack y con los requerimientos! :heavy_check_mark:

2022-11-16 19:33 UTC, merged